config/routes.rb
ElectronicShop::Application.routes.draw do
  get "welcome/index"
  
  resources :items

  resources :carts

  resources :clients

  root 'welcome#index'
  post 'carts/:id' => 'carts#show', as: :show

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :client
	has_and_belongs_to_many :items
	
	def initialize
		@items = []
	end
	
	def add_item(item)
		@items << item
	end

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :carts, dependent: :destroy
	
	validates :user, :presence => true, :uniqueness => true
	
	validates :passw, :presence => true, :length => { :minimum => 8, :message => "Ingrese minimo 8 caracteres" } 

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_and_belongs_to_many :carts
	
	validates :code, :presence => true, :uniqueness => true
	
	validates :valor, :numericality => true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #comentario asdasdasdasdasdasdasdasdasdasd
  
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  
  def find_cart
	session[:cart] ||= Cart.new
  end
  
  def add_to_cart
	@cart = Cart.first
	item = Item.find(params[:id])
	@cart.add_item(item)

  end
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:numitem, :total, :purchased)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:user, :passw, :nombre, :apellido, :birthday, :direccion)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:code, :nombreitem, :descripcion, :color, :valor)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :num_item %><br>
    <%= f.number_field :numitem %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :purchased %><br>
    <%= f.check_box :purchased %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>Numitem</th>
      <th>Total</th>
      <th>Purchased</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.numitem %></td>
        <td><%= cart.total %></td>
        <td><%= cart.purchased %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Tu Carrito de compra</h1>

<ul>
	<% for item in @cart.items %>
		<div id='items'>
			<div class='panel panel-info'>
				<div class='panel-heading'>
					<h2><%= item.nombreitem %></h2>
				</div>
				<div class='panel-body'>
				<h3>Codigo: <%= item.code  %></h3>
				<h2><%= item.descripcion  %></h1>
				<h2>Color: <%= item.color  %></h1>
				<h2>Precio: $<%= item.valor  %></h1>
				</div>
				
			</div>
			
		</div>
	<% end %>
</ul>


<div class='btn-group'>
		<%= link_to 'Añadir Items', items_path, class:'btn btn-default' %>
</div>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :passw %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Passw</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Birthday</th>
      <th>Direccion</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.user %></td>
        <td><%= client.passw %></td>
        <td><%= client.nombre %></td>
        <td><%= client.apellido %></td>
        <td><%= client.birthday %></td>
        <td><%= client.direccion %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @client.user %>
</p>

<p>
  <strong>Passw:</strong>
  <%= @client.passw %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @client.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @client.apellido %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @client.birthday %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @client.direccion %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
		<div class="input-container">
		  <div class="input-group">
			<span class="input-group-addon">Código:</span>
			<%= f.text_field :code ,class:"form-control valid" %>
		  </div>
		  <br>
		  <div class="input-group">
			<span class="input-group-addon">Nombre de dispositivo:</span>
			<%= f.text_field :nombreitem ,class:"form-control valid" %>
		  </div>
		  <br>
		  <div class="input-group">
			<span class="input-group-addon">Descripcion:</span>
			<%= f.text_field :descripcion ,class:"form-control valid" %>
		  </div>
		  <br>
		  <div class="input-group">
			<span class="input-group-addon">Color:</span>
			<%= f.text_field :color ,class:"form-control valid" %>
		  </div>
		  <br>
		  <div class="input-group">
			<span class="input-group-addon">Valor:</span>
			<%= f.text_field :valor ,class:"form-control valid" %>
			<span class="input-group-addon">$</span>
		  </div>
		  <br>
		  
			<%= f.submit %>
		</div>
	  
  
<% end %>

app/views/items/edit.html.erb
<h1 class="titulo-container">Editing item</h1>

<%= render 'form' %>

<div class='btn-group'>
<%= link_to 'Show', @item , class:'btn btn-default'  %> 
<%= link_to 'Back', items_path, class:'btn btn-default'  %>
</div>

app/views/items/index.html.erb
<h1>Lista de dispositivos</h1>

	<% @items.each do |item| %>
		<div id='items'>
			<div class='panel panel-info'>
				<div class='panel-heading'>
					<h2><%= item.nombreitem %></h2>
				</div>
				<div class='panel-body'>
				<h3>Código: <%= item.code  %></h3>
				<h2><%= item.descripcion  %></h1>
				<h2>Color: <%= item.color  %></h1>
				<h2>Precio: $<%= item.valor  %></h1>
				</div>
				<div class='btn-group'>
					<% cart = Cart.find(1) %>
					<%= link_to 'Añadir al Carrito', cart , :action => :add_to_cart, :id => item , class:'btn btn-default' %>
					<%= link_to 'Mostrar', item , class:'btn btn-default' %>
					<%= link_to 'Editar', edit_item_path(item) , class:'btn btn-default' %>
					<%= link_to 'Eliminar', item, method: :delete, data: { confirm: 'Are you sure?' } ,class:'btn btn-default' %>
				</div>
			</div>
			
		</div>
	<% end %>
</ul>

<br>

<%= link_to 'Nuevo dispositivo', new_item_path , class:'btn btn-default' %>

app/views/items/new.html.erb
<h1 class="titulo-container">Nuevo dispositivo electrónico</h1>

<%= render 'form' %>

<div class='btn-group'>
<%= link_to 'Back', items_path, class:'btn btn-default' %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

	<div class='panel-heading'>
		<div id='items'>
		<h2><%= @item.nombreitem %></h2>
		</div>
	
		<div class='panel-body'>
		<h3>Codigo: <%= @item.code  %></h3>
		<h2><%= @item.descripcion  %></h1>
		<h2>Color: <%= @item.color  %></h1>
		<h2>Precio: $<%= @item.valor  %></h1>
		</div>
		<div class='btn-group'>
			<% cart = Cart.find(2) %>
			<%= link_to 'Añadir al Carrito', cart , :action => :add_to_cart, :id => @item , class:'btn btn-default' %>
			<%= link_to 'Editar', edit_item_path(@item), class:'btn btn-default' %>
			<%= link_to 'Atrás', items_path, class:'btn btn-default' %>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Electronic Shop</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class='navbar navbar-default' role="navigation">
	<div class='navbar-header'>
			<%= link_to 'Inicio' , root_path , class:'navbar-brand'%>
			<%= link_to 'Items' , items_path , class:'navbar-brand'%>
			<% cart = Cart.find(1) %>
			<%= link_to 'Cart' , cart , class:'navbar-brand'%>
	</div>
	<p class="navbar-text pull-right">Signed in as <a href="#" class="navbar-link">Mark Otto</a></p>
</nav>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1 class="titulo-container-center">Electronic Shop</h1>